// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace WhatToEat.Domain.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_0));
        
        string IMigrationMetadata.Id
        {
            get { return "201801241758120_0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
